### ISSUE TITLE
bug: DatePicker in EditProfile doesn't have a limit value

### ISSUE THREAD

**Issue by tkhmrv** [Leonid-Korobkov/social-net-front#1]
я дед инсайд еще до рождения💀
всем из 9999 года васап
<img width="426" alt="image" src="https://github.com/user-attachments/assets/0cd1d4a5-a236-4960-baf2-41d0148c2608" />

**Comment by Leonid-Korobkov** [comment]
@tkhmrv Thank you for finding a bug in my wonderful program. I have already fixed it.
